### ISSUE TITLE
Possibility to use the function Generator outside the box?

### ISSUE THREAD

**Issue by NicolasSompairac** [favilaco/deconv_benchmark#2]
Dear @favilaco,

I was wondering if the function `Generator` could be used to generate an individual simulated bulk dataset from scRNAseq in a similar fashion as it is done in Gregor Sturm's benchmark: https://github.com/icbi-lab/immune_deconvolution_benchmark/blob/master/notebooks/15_mixing_study.Rmd

I have tried to make it work but it doesn't seem to be possible to do directly and it would require breaking down the function a little bit (and I am not sure if I would do it properly in the end). Do you think it would be possible extract it and play with the simulated datasets using other methods of deconvolution?

**Comment by favilaco** [comment]
Dear @NicolasSompairac ,

The "Generator" function, in principle, could be used with any dataset as long as it's processed as the 4 we used in the manuscript. Moreover, the "Deconvolution" function can also be enlarged by adding other methods if desired (as another nested "else if" statement, generating an object named "RESULTS" containing the proportions).

Could you tell me where exactly it's giving you an error/where you are encountering difficulties? That way I can adapt the code where needed in order to make it more usable ;)

Thanks!
Francisco

**Comment by favilaco** [comment]
Dear @NicolasSompairac ,

Probably you already saw it, but the function "Generator" from [https://github.com/favilaco/deconv_benchmark/blob/master/helper_functions.R](url) could be use for the purpose you described.

Hope this helps!

Best,
Francisco
